name = "TippingTest"
uuid = "75f7372b-cee4-4a9f-bfee-e1c4ff5740ce"
authors = ["R. Boerner"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
